#!/bin/bash

# Ministra WM Portal auto installer script for Debian and Ubuntu.

# his script will work on Debian, Ubuntu and probably other distros
# of the same families, although no support is offered for them. It isn't
# bulletproof but it will probably work if you simply want to setup a Ministra WM Portal on
# your Debian/Ubuntu box. It has been designed to be as unobtrusive and
# universal as possible.

# This is a free shell script under GNU GPL version 3.0 or above
# Copyright (C) 2017 UmitCanbolat/HOXSEC project.
# Feedback/comment/suggestions : https://www.ucanbolat.nl/
# Author Umit Canbolat a.k.a HOXSEC

# Color schema

red='\033[01;31m'
blue='\033[01;34m'
green='\033[01;32m'
norm='\033[00m'

#ver=v5.3.0
pass="m1n1str4"
source="https://www.ucanbolat.nl/configs"

# ECHO STALKER_PORTAL ASCII :)
clear
echo ""
echo ""
echo "Ministra v5.4.0 Installer by UmitCanbolat.nl aka HOXSEC"
echo ""
echo ""
#Update and Upgrade
echo "Updating and Upgrading"
apt-get update && sudo apt-get upgrade -y

sudo apt-get install -y dialog wget curl sendmail
chmod +x ./lab/*
(
c=20
while [ $c -ne 120 ]
    do
        echo $c
        echo "###"
        echo "$c %"
        echo "###"
        ((c+=20))
        sleep 1
done
) |
dialog --title "Installation will begin shortly" --gauge "Please wait ...." 10 60 0


if [[ $EUID -ne 0 ]]; then
 echo "This script must be run as root" 
 exit 1
else
 cmd=(dialog --separate-output --checklist "Please Select Software you want to install:" 22 76 16)
 options=(1 "Install Ministra Portal" off
 2 "Install Stalker Portal" off
 3 "Install Ministra on Ubuntu 16.04" off
 4 "Exit" off)
 choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
 clear
 for choice in $choices
 do
 case $choice in
 1)
 clear
 echo "Installing Ministra"
 ./lab/ministra
;;
2)
clear
 echo "Installing Stalker"
./lab/stalker
 ;;

3)
clear
 echo "Install Ministra on Ubuntu 16.04"
./lab/ministra16
 ;;

 #Exit
4)
exit
 ;;

 esac
 done
fi